### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.olacabs.customer/com.payu.sdk.ProcessPaymentActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment cbw: make sure class name exists, is public, and has an empty constructor that is public

### ISSUE THREAD

**Issue by riyaz** [payu-intrepos/Android-SDK#9]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.olacabs.customer/com.payu.sdk.ProcessPaymentActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment cbw: make sure class name exists, is public, and has an empty constructor that is public
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2186)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5099)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment cbw: make sure class name exists, is public, and has an empty constructor that is public
       at android.support.v4.app.Fragment.instantiate(Fragment.java:431)
       at android.support.v4.app.FragmentState.instantiate(Fragment.java:101)
       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1833)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:264)
       at com.payu.sdk.ProcessPaymentActivity.onCreate(ProcessPaymentActivity.java:34)
       at android.app.Activity.performCreate(Activity.java:5117)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5099)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.InstantiationException: can't instantiate class cbw; no empty constructor
       at java.lang.Class.newInstanceImpl(Class.java)
       at java.lang.Class.newInstance(Class.java:1319)
       at android.support.v4.app.Fragment.instantiate(Fragment.java:420)
       at android.support.v4.app.FragmentState.instantiate(Fragment.java:101)
       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1833)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:264)
       at com.payu.sdk.ProcessPaymentActivity.onCreate(ProcessPaymentActivity.java:34)
       at android.app.Activity.performCreate(Activity.java:5117)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5099)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

![image](https://cloud.githubusercontent.com/assets/22842/7202734/a1be3896-e532-11e4-8293-9e6f07e24582.png)

**Comment by mayankcool786** [comment]
@Franklin2412 How .. Could you please let us know ?
